Repository OpenSlides/openslides-manage-service, pull requests merged in 2022-02, with the labels that each got.

#157 reflect change in backend
  proto/manage.proto
Labels: backend, management

#158 Fixed proto file.
  pkg/createuser/createuser_test.go
  proto/manage.pb.go
  proto/manage.proto
Labels: high

#156 add get sub-command
  pkg/client/client.go
  pkg/datastorereader/datastorereader.go
  pkg/get/get.go
  pkg/server/server.go
  proto/manage.pb.go
  proto/manage.proto
  proto/manage_grpc.pb.go
Labels: datastore, feature, management
